### ISSUE TITLE
Use with OpenAirInterface5G

### ISSUE THREAD

**Issue by Marcel2508** [ravens/docker-nextepc#3]
Hey,
thanks for this easy-to-deploy Docker-setup.
But What I still don't get is: How could I use my enB with hardware attached with this setup?

I would like to use the openairinterface5g eNB, because it (looks like it) got proper tdd Support.
But I don't see how I would expose my MME's ports to be connected to by my eNB?
Every Port/Host (on the loopback Interface) I tried so far got a connection refused error..

It looks like it binds to the physical LAN Interface and ignores my loopback configuration?

Any tips?

**Comment by ravens** [comment]
Sorry I am just seeing this message now. Behind the scene docker/docker-compose is using network namespace. If you want the real host to see something, you need to adjust your docker to run with --net=host so that the MME port will be exposed. Hope this helps. Closing as this is out of scope of this personal project.
